const probabiliteRealisation  = {
  "*":  "Quasi aucun chance",
  "**":  "Peu de chance",
  "***":  "Incertaine ou échéance lointaine",
  "****":  "Fortes chances",
  "*****":  "Hautement probable",
  "******":  "succès au rendez-vous"
}
const binaryToHexagramme = {
"111111" : {"䷀": 1},
"000000" : {"䷁": 2},
"100010" : {"䷂": 3},
"010001" : {"䷃": 4},
"111010" : {"䷄": 5},
"010111" : {"䷅": 6},
"010000" : {"䷆": 7},
"000010" : {"䷇": 8},
"111011" : {"䷈": 9},
"110111" : {"䷉": 10},
"111000" : {"䷊": 11},
"000111" : {"䷋": 12},
"101111" : {"䷌": 13},
"111101" : {"䷍": 14},
"001000" : {"䷎": 15},
"000100" : {"䷏": 16},
"100110" : {"䷐": 17},
"011001" : {"䷑": 18},
"110000" : {"䷒": 19},
"000011" : {"䷓": 20},
"100101" : {"䷔": 21},
"101001" : {"䷕": 22},
"000001" : {"䷖": 23},
"100000" : {"䷗": 24},
"100111" : {"䷘": 25},
"111001" : {"䷙": 26},
"100001" : {"䷚": 27},
"011110" : {"䷛": 28},
"010010" : {"䷜": 29},
"101101" : {"䷝": 30},
"001110" : {"䷞": 31},
"011100" : {"䷟": 32},
"001111" : {"䷠": 33},
"111100" : {"䷡": 34},
"000101" : {"䷢": 35},
"101000" : {"䷣": 36},
"101011" : {"䷤": 37},
"110101" : {"䷥": 38},
"001010" : {"䷦": 39},
"010100" : {"䷧": 40},
"110001" : {"䷨": 41},
"100011" : {"䷩": 42},
"111110" : {"䷪": 43},
"011111" : {"䷫": 44},
"000110" : {"䷬": 45},
"011000" : {"䷭": 46},
"010110" : {"䷮": 47},
"011010" : {"䷯": 48},
"101110" : {"䷰": 49},
"011101" : {"䷱": 50},
"100100" : {"䷲": 51},
"001001" : {"䷳": 52},
"001011" : {"䷴": 53},
"110100" : {"䷵": 54},
"101100" : {"䷶": 55},
"001101" : {"䷷": 56},
"011011" : {"䷸": 57},
"110110" : {"䷹": 58},
"010011" : {"䷺": 59},
"110010" : {"䷻": 60},
"110011" : {"䷼": 61},
"001100" : {"䷽": 62},
"101010" : {"䷾": 63},
"010101" : {"䷿": 64}
}

const oracle =
{
"䷀" : {
	"nom" : "1. Khien / Qian",
	"titre" : "L'élan céleste / activité / Création",
	"resume" : "La naissance de quelque chose de grand est proche. Vous serez un facteur important dans un nouveau projet qui croitra et se régénèrera pour toujours.",
	"91" : "C’est une période d’attente. Organisez et planifiez votre stratégie pour un succès à venir.",
	"92" : "Vous êtes sur le point de débuter un projet important. Cherchez une personne qui peut aider à en assurer le succès.",
	"93" : "Le travail sans relâche et l’attention portée aux détails vous garantiront l’atteinte de vos buts.",
	"94" : "Une fois prêt, testez vos plans, vous pourrez ainsi les parfaire.",
	"95" : "Votre plan est ou sera un succès. Revisiter vos alliés et cherchez de nouveaux leaders.",
	"96" : "Ne laisser pas vos succès gonfler votre ego démesurément. Si vous le faites, il y aura un prix à payer.",
	"realisation" : "****",
	},
"䷁" : {
	"nom" : "2. Khouen / Kun",
	"titre" : "la terre réceptive / passivité / Approbation",
	"resume" : "Soyez loyal, diligent, humble et modeste dans tous vos engagements. La persévérance conduira à de grandes choses.",
	"61" : "Demeurez prudent et calme.  N’agissez pas sans réflexion préalable. La persévérance est votre alliée.",
	"62" : "Respectez votre éthique. Suivez votre chemin en toute confiance.",
	"63" : "Indépendamment de votre position vous serez respecté et récompensé. Soyez fier de l’état actuel de votre vie.",
	"64" : "Parlez er agissez prudemment et vous ne serez pas vaincu ou châtié.",
	"65" : "Votre avenir est prometteur.",
	"66" : "Vous survivrez aux luttes de pouvoir de votre entourage. Les gagnants vous apporteront le succès.",
	"realisation" : "*****",
	},
"䷂" : {
	"nom" : "3. Tshouen / Tun",
	"titre" : "La difficulté initiale / naissance des êtres / Accumulation",
	"resume" : "Rassemblez vos forces. Prenez de nouvelles directions et allez de l’avant. Vos débuts seront peut-être exigeants, mais par des gestes et des pensées imprégnées de prudence vos buts seront atteints.",
	"91" : "Demeurez concentré sur vos buts. Allez de l’avant avec vos plans. Recherchez l’aide de votre entourage. Déléguez des responsabilités et vous surmonterez tous les obstacles.",
	"62" : "Soyez prudents dans le choix de vos projets. Actuellement, ce n’est peut-être pas le moment de faire un choix.",
	"63" : "Actuellement, il n’est peut-être pas opportun de faire un choix sans être guidé. Faites attention pour ne pas vous égarer.",
	"64" : "Les partenariats vont vous porter chance. Acceptez les offres raisonnables qui se présentent sur votre chemin.",
	"95" : "Faites de petits pas vers vos buts. Les pas de géants risquent d’être désastreux.",
	"66" : "Ne laissez pas les échecs stopper votre progression. Concentrez vos énergies sur ce qui est positif.",
	"realisation" : "****",
	},
"䷃" : {
	"nom" : "4. Mong / Meng",
	"titre" : "le tâtonnement juvénile / développement. de l’intelligence / Ignorance",
	"resume" : "Assurez-vous que vos subordonnés comprennent ce que vous dites. Une structure et des règles strictes vont inspirer la croissance.",
	"61" : "Soyez ferme sans être despote. Guidez ceux qui en ont besoin.",
	"92" : "Soyez patient avec vos subordonnés et informez-les.",
	"63" : "La recherche des seuls gains matériels va vous nuire.",
	"64" : "Gardez votre esprit réceptif aux expériences et connaissances nouvelles.",
	"65" : "Enseignez aux nouveaux par de nobles ambitions.",
	"96" : "Enseignez à ceux qui en connaissent moins que vous.  Ne condamnez pas le premier essai.",
	"realisation" : "***",
	},
"䷄" : {
	"nom" : "5. Su / Xu",
	"titre" : "L'Attente",
	"resume" : "La période actuelle en est une d’observation et d’apprentissage. Patience, honnêteté et diligence vous assurent un avenir brillant. Vous êtes sur le point de débuter un projet important. Votre avenir semble prometteur.",
	"91" : "Évitez les ennemies. Soyez patient. N’agissez pas impulsivement.",
	"92" : "Vous êtes prêt à passer à l’action. Faites-le prudemment, mais ne laissez pas passer le moment.",
	"93" : "Vous êtes vulnérable envers ceux qui profiteront de vous. L’isolement est votre ennemi. Entretenez les alliés qui vous pensent comme vous. Vous pourriez être coincés.",
	"64" : "Soyez prêt à agir rapidement et à abandonner les engagements futurs.",
	"95" : "Vous êtes actuellement au bon endroit. Soyez patient. Des évènements positifs vont se présenter sur votre chemin.",
	"66" : "Saisissez les opportunités inattendues.",
	"realisation" : "****",
	},
"䷅" : {
	"nom" : "6. Song / Sung",
	"titre" : "Le conflit / le doute / Confrontation",
	"resume" : "Ne pas utiliser la force et ne pas initier de conflit d’aucune sorte. Recherchez des compromis.",
	"61" : "Exposez votre cause au public et non aux tribunaux.",
	"92" : "Ne vous engagez pas dans des batailles que vous ne pouvez pas gagner.",
	"63" : "Mettez sur pied votre propre entreprise. Lassez tomber les relations chancelantes.",
	"94" : "Évitez les conflits avec les railleurs et le irrationnels.",
	"95" : "Faites valoir votre point de vue et attendez-vous à des rétroactions positives.",
	"96" : "Vous éprouverez des difficultés à court terme. Soyez patient.",
	"realisation" : "**",
	},
"䷆" : {
	"nom" : "7.  Shi",
	"titre" : "L'armée / le groupement de la foule / Mobilisation des troupes",
	"resume" : "Poursuivez vos buts avec confiance et détermination. Rassemblez vos alliés. Évitez les erreurs.",
	"61" : "Appuyez vous sur l’organisation pour vaincre le chaos. Gardez les affaires sous contrôle. Sélectionner des gens compétents pour vous assister.",
	"92" : "Vos tâches seront importantes et vos talents seront appréciés.",
	"63" : "Évitez l'erreurs catastrophique.",
	"64" : "Ne posez pas de gestes important aussi longtemps que vous et vos alliés ne serez pas prêts. Renforcez vos maillons les plus faibles.",
	"65" : "De petites victoires sont préférables à aucune victoire. Recherchez les trêves et les réconciliations.",
	"66" : "Une fois votre but atteint vous passerez à un niveau plus élevé. Demeurez dans un entourage de gens intelligents.",
	"realisation" : "*",
	},
"䷇" : {
	"nom" : "8. Pi / Bi",
	"titre" : "la solidarité / l’association / Alliance",
	"resume" : "Actuellement c’est le bon moment pour initier des partenariats, se faire de nouveaux amis et rechercher de nouvelles expériences.",
	"61" : "La bienveillance est votre alliée. Les bonnes choses arrivent aux bonnes personnes.",
	"62" : "Entretenez les relations durables. Ne brûlez pas les ponts derrière vous.",
	"63" : "Faites que vos ennemis deviennent de bons amis ; que les situations négatives tournent en situations positives.",
	"64" : "Faites du réseautage au-delà de votre organisation. Demandez de l’aide à ceux en qui vous avez confiance.",
	"95" : "Ne soyez pas insupportable. Vous pourriez vous mettre à dos ceux qui croient en votre volonté de changement.",
	"66" : "Demeurez un leader fort, tout en cherchant un successeur afin d’assurer le succès à long terme du projet.",
	"realisation" : "******",
	},
"䷈" : {
	"nom" : "9. Siao tshou / Xiao Chu",
	"titre" : "Le doux apprivoisement / petit arrêt / Petites pauses",
	"resume" : "Le temps d’agir est proche!",
	"91" : "Protégez ce que vous avez déjà. Ne soyez pas prétentieux. Demeurez concentré.",
	"92" : "Reconnaissez ceux qui le mérite. Ne soyez pas dépensier. Récompensez ceux qui vous ont aidé. L’attention que vous porterez à votre entourage immédiat vous amènera à des niveaux plus élevés.",
	"93" : "Ne vous quereller pas et ne créer pas de conflit. La seule façon de progresser est par l’entente.",
	"64" : "Ne vous mêlez pas des batailles sans de bonnes raisons.",
	"95" : "Demeurez déterminé et enthousiaste. Les autres vont se rallier à votre cause.",
	"96" : "Assurez-vous que vos alliés comprennent vos idées. Préparez-vous à lancer de nouveaux projets.",
	"realisation" : "***",
	},
"䷉" : {
	"nom" : "10. Li / Lu",
	"titre" : "La marche périlleuse / les règles rituelles / Marcher",
	"resume" : "Tester vos plans avant de les implanter complètement.",
	"91" : "En ce moment, appuyez-vous sur une approche prudente.",
	"92" : "Demeurez centré. Les diversions peuvent vous nuire.",
	"63" : "Présenter des plans mal fondés ; en prendre plus que ce que vous êtes capable d'accomplir et la folie des grandeurs peuvent vous faire mal.",
	"94" : "Lorsque vous êtes prêts avancez prudemment. Seuls les plus compétents vont survivre. Vous devez réussir.",
	"95" : "Une mauvaise préparation peut vous mener au désastre.",
	"96" : "Examiner vos travaux avec beaucoup de soins. Faire de votre mieux est votre meilleure garantie de succès.",
	"realisation" : "***",
	},
"䷊" : {
	"nom" : "11. Thae / Tai",
	"titre" : "la paix / prospérité / Paix",
	"resume" : "Ne vous en faites pas pour les contretemps. Vous êtes sur la bonne voie. Demeurez centré et éthique.",
	"91" : "Ne laissez pas les individus pessimistes vous abattre. Entourez-vous de personnes optimistes.",
	"92" : "Récompensez les plus compétents. Ne donnez pas de promotion à ceux qui ne le méritent pas.",
	"93" : "Demeurez ferme pendant les périodes difficiles. Des temps meilleurs s’en viennent pour vous.",
	"64" : "Une expérience merveilleuse pourrait vous arriver. Utilisez vos alliées afin d’assurer le succès de vos idées. Partagez la richesse.",
	"65" : "Formez des partenariats ou fusionnez avec des entreprises qui vous ressemblent.",
	"66" : "Réglez les problèmes domestiques  de l’intérieur. Éliminez la trahison et la malhonnêteté.",
	"realisation" : "******",
	},
"䷋" : {
	"nom" : "12. P’ i / Pi",
	"titre" : "La stagnation / décadence / Adversité",
	"resume" : "Ne laissez pas des gens oppressifs bloquer votre développement. Libérez-vous de leur influence.",
	"61" : "Les résultats seront positifs si vous vous dissociez des gens malhonnêtes et pervers.",
	"62" : "Ne jouez pas la carte de la flatterie. Vous en seriez certainement corrompu. Demeurez honnête avec vous-même et avec les autres.",
	"63" : "Attention à la tromperie et éloignez vous de ceux dont les paroles de sont pas conformes au comportement.",
	"94" : "Assumez la responsabilité du changement. Faites de votre environnement un meilleur milieu de vie.",
	"95" : "Avancez avec vos alliés à l’unisson. Le succès va venir.",
	"96" : "Tous les obstacles vont être surmontés. Le succès vous attend.",
	"realisation" : "*",
	},
"䷌" : {
	"nom" : "13. Thong jen / Tong Ren",
	"titre" : "la fraternité / identité des hommes / Rassembler les gens",
	"resume" : "Tranquillement, rassemblez vos alliés. Préparez-vous à transposer vos idées dans la réalité. Une grande aventure se prépare devant vous.",
	"91" : "Faites-vous de nouveaux amis et partenaires. Ils vont vous introduire à de nouveaux prospects.",
	"62" : "Ne craignez pas les nouveaux partenariats et les nouvelles alliances.",
	"93" : "Comprenez vos compétiteurs. Ne frappez pas avant de pouvoir réussir.",
	"94" : "L’humilité et l’entregent sont d’admirables qualités. N’humiliez pas ceux que vous avez vaincus.",
	"95" : "Une fois vos buts atteints, célébrez votre succès dans la joie.",
	"96" : "Lorsque vous gagnez manifestez de la compassion envers les perdants.",
	"realisation" : "****",
	},
"䷍" : {
	"nom" : "14. Tae yeou / Da You",
	"titre" : "Le grand avoir / Récompense",
	"resume" : "Vous êtes dans une période de grande récompense et de prospérité. Vous serez reconnu pour vos contributions. Ne vous permettez pas de vous croire trop important.",
	"91" : "Ne sous estimez jamais vos compétiteurs. Des moments difficiles vont surgir.",
	"92" : "Recherchez du support pour assurer votre succès.",
	"93" : "Attendez-vous à être récompensé pour un travail bien fait.",
	"94" : "L’humilité va vous permettre d’éviter la jalousie et les racontars des autres.",
	"65" : "Traitez les autres comme vous aimeriez être traité.",
	"96" : "Vous serez un leader. De bonnes choses vous attendent.",
	"realisation" : "******",
	},
"䷎" : {
	"nom" : "15. Khien / Qian",
	"titre" : "L'insuffisance / Modestie",
	"resume" : "Demeurez modeste et ne vous laissez pas entrainer pas votre fierté. Agissez dignement peu importe votre position.",
	"61" : "Ne vous vantez pas. Avancez tranquillement vers votre but.",
	"62" : "L’humilité va assurer votre chance.",
	"93" : "Travaillez avec soin et diligence.",
	"64" : "Suivez l’exemple de ceux que vous admirez.",
	"65" : "Pour avoir un large support, soyez juste envers tous et chacun.",
	"66" : "L’humilité vous assure de grandes réalisations. Parlez à tous ceux qui veulent vous adresser la parole.",
	"realisation" : "***",
	},
"䷏" : {
	"nom" : "16. Yu",
	"titre" : "L'enthousiasme / Satisfaction",
	"resume" : "Fiez-vous à votre instinct. Posez des gestes quand vous croyez que le moment est venu.",
	"61" : "Soyez toujours prêt. Continuez à faire du bon travail.",
	"62" : "Cherchez des solutions immédiates aux obstacles qui se présentent sur votre chemin.",
	"63" : "Pas de procrastination, les pertes de temps nuiront à vos projets.",
	"94" : "Ne doutez pas de vos actions et de vos décisions. Vous ferez ce qu’il faut. Réjouissez-vous de votre succès.",
	"65" : "Maintenez votre éthique. Corrigez vos erreurs et renforcez vos points faibles.",
	"66" : "Préparez-vous pour un nouveau projet.  Vous reposer sur vos lauriers pourrait vous nuire.",
	"realisation" : "****",
	},
"䷐" : {
	"nom" : "17. Souei / Sui",
	"titre" : "La suite / Suivre",
	"resume" : "Suivez votre destin sans hésitation. Amenez vos idées à maturité. Respectez résolument vos normes d’éthique. Le succès approche.",
	"91" : "Quand vous dirigez, cherchez des alliés. Soyez vrai face à vous-même afin de favoriser votre succès.",
	"62" : "Ne perdez pas votre temps avec ceux qui n’en valent pas la peine.",
	"63" : "Cherchez le bien ainsi le mal vous évitera.",
	"94" : "Soyez sélectif dans vos alliances. Formez vos subordonnés avant de leur confier des responsabilités.",
	"95" : "Avancez vers vos buts sans crainte. La sincérité va vous attirer des amis.",
	"66" : "Fixez les normes et les règles. Vos buts sont sur le point d’être atteints.",
	"realisation" : "*****",
	},
"䷑" : {
	"nom" : "18. Kou / Gu",
	"titre" : "Le travail sur le déclin / les causes / Dégradation",
	"resume" : "Quittez les situations qui se dégradent. Fixez de nouveaux objectifs et des règles de base.",
	"61" : "Soyez agressif dans vos efforts. Corrigez les erreurs. Évitez de développer une mauvaise attitude. Attendez-vous à réussir.",
	"92" : "Débarrassez-vous du bois mort. Préparez-vous à croître.",
	"93" : "Ne vous arrêtez pas aux échecs antérieurs ou aux relations désastreuses. Essayez de bien faire.",
	"64" : "Ne faites pas confiance à des gens douteux. Recherchez des alliés compétents.",
	"65" : "Construisez vous une réputation honorable. Cela vous vaudra respect et admiration.",
	"96" : "Si vous atteignez de nouveaux sommets, ne vous attendez pas à ce que les alliés de vos prédécesseurs vous suivent.",
	"realisation" : "**",
	},
"䷒" : {
	"nom" : "19. Lin",
	"titre" : "La montée de puissance / troubles et surveillance /Arrivée",
	"resume" : "Axez vos priorités sur la santé et les finances. Attendez-vous à des difficultés et des défis.",
	"91" : "Vos réussites seront reconnues. Attendez-vous à des éloges de votre famille et de vos associés.",
	"92" : "Demeurez ferme dans vos décisions. Un grand moment approche.",
	"63" : "Vous êtes sur le point d’entrer sous les feux de la rampe. Soyez patient. Le soin apporté à votre préparation est votre garantie que tout ira bien.",
	"64" : "Votre travail acharné et votre persistance ont été récompensés. Félicitations !",
	"65" : "Respectez vos amis et vos associés. Montrez votre meilleur profil.",
	"66" : "Soyez gentil et compatissant envers ceux que vous avez vaincus. Respectez vos amis et votre famille.",
	"realisation" : "******",
	},
"䷓" : {
	"nom" : "20. Kouan / Guan",
	"titre" : "La contemplation / l’objet de l’observation / Observation",
	"resume" : "Ne prenez pas de décisions impulsives. Observez les comportements des autres avant d’en faire vos alliés. Prenez le chemin qui vous semble le meilleur pour vous.",
	"61" : "Choisissez votre parcours soigneusement. Demandez-vous s’il sera ultimement satisfaisant. Faites la même chose avec vos relations.",
	"62" : "Au début d’une relation, suivez votre cœur et votre intuition.",
	"63" : "Prenez conscience de vos habiletés et de vos limites avant d’accepter de nouvelles responsabilités.",
	"64" : "N’acceptez pas les opportunités douteuses.",
	"95" : "Développez une solide éthique de travail basée sur l’intégrité et l’équité. Devenez un mentor pour votre entourage.",
	"96" : "La compréhension des éléments de vos relations tant personnelles que d’affaires vont favoriser leur développement.",
	"realisation" : "***",
	},
"䷔" : {
	"nom" : "21. She ho / Shi He",
	"titre" : "Mordre au travers / couper court à l’erreur / Mastication",
	"resume" : "N’entrez pas dans de nouvelles affaires sans un contrat blindé.",
	"91" : "Assurez-vous que la sanction est proportionnelle à la faute.",
	"62" : "Soyez équitable avec les autres. Ne montez pas les choses en épingle.",
	"63" : "Soyez équitable. Demeurez ferme dans vos jugements. Gardez vos distances de ceux qui pourraient nuire à vos efforts.",
	"94" : "Faites part de vos décisions en toute confiance. Recherchez l’approbation de vos supérieurs.",
	"65" : "Respectez votre éthique même sous la pression. Soyez toujours équitable.",
	"96" : "Donnez aux autres une seconde chance. Votre gentillesse vous apportera de bonnes choses.",
	"realisation" : "***",
	},
"䷕" : {
	"nom" : "22. Pi / Bi",
	"titre" : "La grâce / orner et régulariser / Embellir",
	"resume" : "Recherchez de nouvelles connaissances et niveaux de conscience. Réparez vos relations et vos propriétés.",
	"91" : "Prenez grand soin de votre corps et de votre esprit.",
	"62" : "Faites de votre mieux dans tous vos essais. Soignez votre apparence et nourrissez votre amour propre.",
	"93" : "Dépensez votre argent afin de mieux vivre, mais n’oubliez jamais que les biens matériels ne sont pas une fin en eux-mêmes.",
	"64" : "Ne soutirez pas d’avantage des autres. Assurez-vous que vos propositions bénéficient à toutes les parties concernées. Ne soyez pas flamboyant.",
	"65" : "N’adoptez pas un style de vie trop exubérant. Récoltez les récompenses de vos investissements avec intelligence.",
	"96" : "N’en mettez pas plus qu’il ne faut. Demeurez simple. Dites la vérité.",
	"realisation" : "****",
	},
"䷖" : {
	"nom" : "23. Po / Bo",
	"titre" : "La décadence / user peu à peu, déclin / Éclatement",
	"resume" : "Acceptez le changement. Centrez-vous sur la correction des problèmes qui retardent votre développement. Remettez vos relations sur les rails.",
	"61" : "Portez attention à vos subordonnés.",
	"62" : "Renforcez vos fondations avant que tout ne soit perdu.",
	"63" : "Quittez les projets qui se dirigent vers l’échec. Soyez à l’affut de nouvelles opportunités.",
	"64" : "Votre position peut être dangereuse. Dégagez-vous des entreprises qui voguent vers l’échec.",
	"65" : "Quittez ceux qui pourraient vous faire du mal.",
	"96" : "Demeurez intègre pendant les périodes difficiles. Ne vous écartez pas de votre chemin et de bonnes choses vont vous arriver.",
	"realisation" : "*",
	},
"䷗" : {
	"nom" : "24. Fou / Fu",
	"titre" : "Le tournant / retour en sens opposé / Retour",
	"resume" : "Les difficultés vont passées rapidement. La chance va vous sourire.",
	"91" : "Ne vous attardez aux échecs. Corrigez vos erreurs et allez de l’avant avec assurance.",
	"62" : "Prenez une pause. Relaxez. Essayez de pardonner et d’oublier les offenses passées.",
	"63" : "Ne laissez pas les faux départs vous décourager. Demeurez dans la course et vous réussirez.",
	"64" : "Demeurez résolu. Ne suivez pas ceux qui ont fait de mauvais choix.",
	"65" : "Admettez vos erreurs et corrigez les.",
	"66" : "Cherchez dans votre planification les erreurs qui pourraient vous nuire.",
	"realisation" : "*****",
	},
"䷘" : {
	"nom" : "25. Wou wang / Wu Wang",
	"titre" : "La non-errance / absence d’irrégularité / Innocence",
	"resume" : "Gardez vos distances des mécréants. Demeurez respectable et tout ira bien.",
	"91" : "Si vous êtes sûr de poser des actions correctes, allez y sans crainte.",
	"62" : "Recherchez un mentor. Travaillez à l’intérieur de vos champs de compétences.",
	"63" : "Vous rencontrerez peut-être des contre temps. Demeurez fidèle à vous-même et ils passeront.",
	"94" : "Faites confiance en l’avenir.",
	"95" : "Ne prenez pas les rumeurs au sérieux. Suivez votre plan et vous réussirez.",
	"96" : "Soyez prudent. Ne bougez pas avant d’être sûr d’être prêt.",
	"realisation" : "***",
	},
"䷙" : {
	"nom" : "26. Tae tsou / Da Chu",
	"titre" : "Le ferme apprivoisement / grand arrêt / Gains importants",
	"resume" : "Le temps est plus propice à l’action qu’à la réflexion. La procrastination pourrait compromettre votre réussite.",
	"91" : "Soyez prudent. Prévoyez l’imprévisible.",
	"92" : "Vos habiletés ne peuvent être restreintes. Allez de l’avant avec vos plans.",
	"93" : "Votre projet sera un succès.",
	"64" : "L’attention que vous porterez aux détails est un gage de réussite de votre tâche.",
	"65" : "Restez en contrôle et ne vous laissez pas influencer pas les placotages et les rumeurs.",
	"96" : "Vous accomplirez une tâche importante.",
	"realisation" : "***",
	},
"䷚" : {
	"nom" : "27. Yi",
	"titre" : "L'entretien de la vie / la nourriture / Paroles",
	"resume" : "Parlez simplement et avec sincérité. Nourrissez vos espoirs et vos rêves. Prenez soin de votre entourage. Faites le bien.",
	"91" : "Évitez l’envie et la jalousie. Soyez fier de vos réussites.",
	"62" : "Donnez une chance aux gens talentueux. Cherchez les racines qui vous donnent la force.",
	"63" : "Ne choisissez pas vos partenaires sur la base de leur statut financier.",
	"64" : "N’accordez pas de faveurs non méritées. Ne laissez pas les autres influencer vos décisions.",
	"65" : "Collez-vous à vos idéaux. Avancez lentement vers de nouvelles tentatives.",
	"96" : "Mettez vos idées en pratique. C’est le temps de réaliser vos buts.",
	"realisation" : "***",
	},
"䷛" : {
	"nom" : "28. Tae kuo / Da Guo",
	"titre" : "la prépondérance du grand / ce qui est grand traverse / Grand examen",
	"resume" : "Vous pourrez vous retrouver dans une situation compromettante. Vos relations et vos projets pourraient être proche de l’effondrement. Il est le temps de regarder d’autres opportunités.",
	"61" : "Obtenez l’appui et la confiance des autres en démontrant vos bonnes intentions. L’humilité est votre allié.",
	"92" : "Soyez courageux face à l’adversité. Vous surmonterez tous les obstacles.",
	"93" : "Le chemin est peut-être chaotique et dangereux. Si c’est le cas, soyez prudent.",
	"94" : "Vos problèmes ne sont pas si gros qu’ils le paraissent. Cependant, à l’avenir pour évitez les troubles. Traitez-les prudemment.",
	"95" : "Tirez avantage de ceux qui ne sont pas dignes n’est pas noble.",
	"66" : "Fiez-vous à votre intuition, votre diligence et votre courage pour vous aider dans les moments difficiles.",
	"realisation" : "*",
	},
"䷜" : {
	"nom" : "29. Khan / Kan",
	"titre" : "L'eau insondable / chute dans l’abîme / Caverne",
	"resume" : "Recherchez l’aide de vos alliés. Prenez les choses en mains et avancez avec confiance.",
	"61" : "Adaptez-vous aux conditions actuelles. Soyez patient et la tempête va passer.",
	"92" : "Avancez à petits pas vers votre but. La patience et le travail acharné vous feront surmonter les obstacles.",
	"63" : "Restez calme. Soyez vrai face à vous-même.",
	"64" : "Soyez frugal et pratiquez la simplicité.",
	"95" : "Les problèmes auxquels vous faites face seront bientôt chose du passé.",
	"66" : "Bien que vos problèmes semblent profondément ancrés, ils passeront.",
	"realisation" : "*",
	},
"䷝" : {
	"nom" : "30. Li",
	"titre" : "Le feu qui s'attache / jonction et séparation / Intelligence",
	"resume" : "Révélez vos intentions. Donnez libre cours à votre charisme. Votre futur s’annonce étincelant.",
	"91" : "Ne perdez pas de vue vos objectifs, vos amis et votre réseau.",
	"62" : "Recherchez les personnes modestes et diligentes pour vous assister dans vos efforts.",
	"93" : "Assurez-vous que vos subordonnés appliqueront vos directives.",
	"94" : "Certaines de vos relations font disparaître aussi vite qu’elles sont apparues.",
	"65" : "Prenez soin des gens de talent de la même façon que ceux que vous aimez. C’est votre gage de succès.",
	"96" : "Soyez gentil avec les autres, mais ne laissez personne compromettre votre progression.",
	"realisation" : "****",
	},
"䷞" : {
	"nom" : "31. Hien / Xian",
	"titre" : "L'influence",
	"resume" : "Observez les gens autour de vous. Assurez-vous leur loyauté par votre intégrité.",
	"61" : "Saisissez les intentions des autres avant de vous en faire des alliés.",
	"62" : "Ne devenez pas amis avec ceux dont vous ne comprenez pas la motivation.",
	"93" : "Cherchez la vérité. Faites ce que vous croyez être bien.",
	"94" : "Ne soyez pas indécis. Suivez votre plan.",
	"95" : "Encouragez les gens qui vous entourent. Soulignez leurs réalisations.",
	"66" : "La compréhension mutuelle mène à des amitiés et des partenariats satisfaisants.",
	"realisation" : "*****",
	},
"䷟" : {
	"nom" : "32.  Heng",
	"titre" : "La pérennité / perpétuité / Durée",
	"resume" : "Renforcez vos relations et vos amitiés. Une base solide garantie le succès.",
	"61" : "Laissez de la place aux autres. Ne déterminez pas les sujets de discussion.",
	"92" : "Ne vous attardez pas sur le passé. Prenez un nouveau départ.",
	"93" : "Respectez votre morale. Évitez ceux qui ne le font pas.",
	"94" : "Ne poursuivez pas d’objectifs de peu de valeur. Recherchez des alliés valables.",
	"65" : "Choisissez vos amis avec intelligence.",
	"66" : "Abandonnez les relations défaillantes.",
	"realisation" : "****",
	},
"䷠" : {
	"nom" : "33. Thouen / Tun",
	"titre" : "La retraite / se retirer en arrière / Retrait",
	"resume" : "Prenez de votre temps pour mesurer vos progrès et vos buts. Évaluez vos amis et coupez dans le bois mort si nécessaire.",
	"61" : "Abandonnez les relations insatisfaisantes.",
	"62" : "Suivez votre chemin sans regarder en arrière.",
	"93" : "Ne laissez pas vos besoins d’être conseillé par d’autres vous épuiser.",
	"94" : "Retirez vous des relations qui ne mènent nulle part. Le doute est votre ennemi.",
	"95" : "Ne vous associez pas à des personnes que vous n’aimez pas. Ainsi vous serez en paix.",
	"96" : "Quittez les mauvaises relations. Votre courage sera récompensé.",
	"realisation" : "*",
	},
"䷡" : {
	"nom" : "34. Ta tshang / Da Zhuang",
	"titre" : "La puissance du grand / parfait épanouissement / Puissance",
	"resume" : "Votre intégrité, votre persévérance et votre minutie vous vaudront de l’admiration. Mettez de l’avant de nouvelles idées.",
	"91" : "Utilisez vos talents. Ne vous retirez pas et ne soyez pas trop modeste.",
	"92" : "Prenez votre place et vous vaincrez.",
	"93" : "Ne poursuivez pas des actions qui n’en valent pas la peine. Concentrez-vous sur des opportunités qui vous élèveront vers de nouveaux sommets.",
	"94" : "Passez à l’action lorsque vous êtes sûr d’être prêt.",
	"65" : "Il y aura des difficultés, mais vous serez persévérant.",
	"66" : "Soyez patient et votre bon travail sera récompensé éventuellement.",
	"realisation" : "****",
	},
"䷢" : {
	"nom" : "35. Tsin / Jin",
	"titre" : "Le Progrès / progression en avant",
	"resume" : "Vous êtes en ascension,",
	"61" : "Soyez aimable avec tout le monde et vous connaîtrez le succès.",
	"62" : "Quand vous atteindrez d’autres niveaux, des problèmes pourront se présenter. Mais vous vous en sortirez.",
	"63" : "Vous gagnerez la confiance et le respect des autres.",
	"94" : "La démonstration de vos talents calmera les doutes des autres.",
	"65" : "Vous êtes dans une position très stable. Continuez tel que vous êtes.",
	"96" : "Exercez votre autorité pour maintenir conserver votre place. Punissez les fautifs mais ne soyez pas excessif.",
	"realisation" : "***",
	},
"䷣" : {
	"nom" : "36. Ming Yi",
	"titre" : "L'Obscurcissement /  blessure",
	"resume" : "Demeurez optimiste. Les choses vont allez en s’améliorant.",
	"91" : "Ne laissez pas les problèmes assombrir votre esprit. Maintenez vos principes.",
	"62" : "Laissez vos alliés vous aider par temps troubles.",
	"93" : "Ne restez pas passif face aux situations troubles. Agissez!",
	"64" : "Laissez les mauvaises situations derrière vous.",
	"65" : "Soyez patient.",
	"66" : "Soyez prudent et évitez les mauvaises décisions.",
	"realisation" : "*",
	},
"䷤" : {
	"nom" : "37. Kia jen / Jia Ren",
	"titre" : "Le clan familial / hommes de la famille / Famille",
	"resume" : "Comprenez votre position et vos responsabilités dans votre famille. Restez à l’intérieur de vos limites.",
	"91" : "Établissez des règles afin d’éviter le chaos.",
	"62" : "Gardez vos affaires en ordres, ainsi vous pourrez vous concentrer sur vos buts.",
	"93" : "Des règles rigides feront travailler tout le monde plus fort. Ne renvoyez pas au lendemain.",
	"64" : "Le succès arrive en travaillant tous ensemble.",
	"95" : "Soyez fier de vos responsabilités et assumez les correctement.",
	"96" : "Dirigez bien. Soyez ferme, mais équitable et sincère.",
	"realisation" : "****",
	},
"䷥" : {
	"nom" : "38. Khouei / Kui",
	"titre" : "Opposition",
	"resume" : "Ne cherchez pas à gagner de grandes batailles en ce moment.",
	"91" : "N’essayez pas de rétablir de vielles relations.",
	"92" : "Essayez de résoudre les différends dans les relations actuelles.",
	"63" : "Il est possible que vous perdiez du terrain mais vous persévèrerez.",
	"94" : "Il pourrait y avoir des temps difficiles à l’horizon. Recherchez la sagesse dans votre entourage.",
	"65" : "Ne gardez pas rancune. Vivez votre vie.",
	"96" : "N’ayez pas peur de vous faire de nouveaux amis et alliés.",
	"realisation" : "***",
	},
"䷦" : {
	"nom" : "39. Kien / Jian",
	"titre" : "L'obstacle / difficulté / Obstruction",
	"resume" : "Prenez conseil d’une personne à qui vous faites confiance. Il va vous assister dans vos difficultés.",
	"61" : "Soyez prudent et n’agissez pas avant que le moment soit propice.",
	"62" : "Demeurez vrai face à vous-même et à vos principes même face à l’adversité.",
	"93" : "Les mauvais jours vont passer.",
	"64" : "Ne jouez pas les martyres. Demandez de l’aide lorsque vous vous sentez submergé.",
	"95" : "N’ayez pas peur de demander de l’aide.",
	"66" : "Seule l’aide de ceux à qui vous faites confiance va vous aider à passer à travers. N’agissez pas avant d’être prêt.",
	"realisation" : "***",
	},
"䷧" : {
	"nom" : "40. Kiae / Jie",
	"titre" : "Libération / délivrance / Séparation",
	"resume" : "Même sans soutien, vos plans vont porter fruit.",
	"61" : "Avancez vers vos buts avec confiance.",
	"92" : "Demeurez intègre. Centrez vous sur vos buts et vous serez bien.",
	"63" : "Diversifiez, ne vous fiez pas à un seul chemin pour trouver le succès.",
	"94" : "Le moment d’agir c’est maintenant. Une grande aventure vous attend.",
	"65" : "Allez de l’avant avec vos idées avec optimiste.",
	"66" : "Coupez les liens avec ceux qui vous ont trahis. Procédez avec assurance.",
	"realisation" : "**",
	},
"䷨" : {
	"nom" : "41. Souen / Sun",
	"titre" : "Diminution / Décroissance",
	"resume" : "Respectez un budget serré. Évitez les frivolités et vous atteindrez vos buts.",
	"91" : "Prenez soin des autres et ils prendront soin de vous.",
	"92" : "Épargnez de l’argent pour les besoins à venir. Élaborez un budget.",
	"63" : "Travaillez en tant qu’individu mais laissez les autres vous donner un coup de main.",
	"64" : "Attendez vous à améliorer votre situation et à célébrer.",
	"65" : "Votre leadership va assurer votre prospérité et celle des autres.",
	"96" : "Attendez vous à être traiter comme vous traitez les autres.",
	"realisation" : "****",
	},
"䷩" : {
	"nom" : "42.  Yi",
	"titre" : "L'accroissement / Croissance",
	"resume" : "Une fois la prospérité atteinte, poursuivez des buts qui étaient jusque là hors de portée. Investissez dans votre avenir.",
	"91" : "Ne dépensez pas inutilement. Supportez de bonnes causes. Les résultats vont vous apporter de la satisfaction.",
	"62" : "Soyez un bénévole, un mentor, une personne généreuse avec son argent.",
	"63" : "Demandez à vos alliés du financement si nécessaire.",
	"64" : "Recherchez de nouveaux projets.",
	"95" : "Acquittez vous de vos tâches avec intégrité et équité.",
	"96" : "Faites attention de ne pas être mal interprété.",
	"realisation" : "*****",
	},
"䷪" : {
	"nom" : "43. Kouae / Guai",
	"titre" : "La percée / Détermination / Résolution",
	"resume" : "Présentez votre cas à vos opposants. Battez vous pour vos croyances.",
	"91" : "Cherchez des alliances auprès de personnes influentes.",
	"92" : "Soyez prudent. Ne commettez pas d’erreur.",
	"93" : "Ignorez la diffamation. Conservez votre étique et la mauvaises période passera.",
	"94" : "Apprenez de vos erreurs et recherchez les bons conseils.",
	"95" : "Éliminez l’immoralité de votre vie.",
	"66" : "Marchez de nouveau vers vos buts. Si le succès de vient pas, repensez votre stratégie.",
	"realisation" : "**",
	},
"䷫" : {
	"nom" : "44. Keou / Gou",
	"titre" : "Venir à la rencontre / Rencontre",
	"resume" : "Jugez les gens selon ce qu’ils sont et non selon leur beauté extérieure.",
	"61" : "Choisissez soigneusement vos amis et vos connaissances.",
	"92" : "Évitez la compagnie des gens malicieux.",
	"93" : "Soyez vigilant envers les gens à la morale douteuse, mais laissez à ceux qui le mérite une seconde chance.",
	"94" : "Tenez vous debout face à l’immoralité et à l’attitude négative.",
	"95" : "Entourez vous de personnes intelligentes et fiables. Soyez humble.",
	"96" : "Tirez avantage de la vanité des autres.",
	"realisation" : "***",
	},
"䷬" : {
	"nom" : "45. Tsouei / Cui",
	"titre" : "Rassemblement / Réunion",
	"resume" : "Travaillez avec ceux que vous croyez capables de grandes réalisations.",
	"61" : "Tirez avantage d’une morale élevée. Marchez vers vos buts.",
	"62" : "Demeurez sincère. Le succès est à votre portée.",
	"63" : "Comprenez bien la position de vos opposants.",
	"94" : "Poursuivez votre chemin actuel et vous réussirez.",
	"95" : "Vos idées seront bien reçues par la plupart des autres.",
	"66" : "Même si certains ne sont pas d’accord avec vous, poursuivez sur votre voie.",
	"realisation" : "******",
	},
"䷭" : {
	"nom" : "46. Sheng",
	"titre" : "Poussée vers le haut / Naissance/ Élévation /Ascension",
	"resume" : "Vous réussirez à atteindre vos buts. Félicitations!",
	"61" : "Votre gentillesse et votre vertu sont vos gages de succès.",
	"92" : "Partagez votre succès avec les autres.",
	"93" : "Travaillez avec des gens de valeur à l’atteinte de vos buts.",
	"64" : "Soyez prêt et le succès deviendra inévitable.",
	"65" : "Demeurez centré. Ne laissez pas le succès gonfler votre ego. Dirigez vous avec constance vers vos buts.",
	"66" : "Demeurez centré. Ne laissez pas le succès vous écarter de votre route.",
	"realisation" : "***",
	},
"䷮" : {
	"nom" : "47. Khouen / Kun",
	"titre" : "l'accablement / misère",
	"resume" : "Demeurez optimiste face à l’adversité.",
	"61" : "Des erreurs dans votre approche pourront provoquer des revers.",
	"92" : "Ne prenez pas de décisions impulsives en ce qui concerne des choses importantes. Restez calme et réfléchi.",
	"63" : "Soyez discret. Développez seul un plan pour résoudre vos problèmes.",
	"94" : "Soyez patient. Le moment venu, l’aide arrivera.",
	"95" : "Vous pourrez perdre du terrain. N’agissez pas malicieusement. Acceptez vos pertes et allez vers de nouvelles choses.",
	"66" : "Évaluez votre prochain geste. Ne répétez pas les vieilles erreurs. Bougez soigneusement et avec optimisme, les résultats seront positifs.",
	"realisation" : "*",
	},
"䷯" : {
	"nom" : "48. Tsing / Jing",
	"titre" : "Le Puits",
	"resume" : "Le temps est venu de consulter les autres et de former de nouvelles alliances.",
	"61" : "Débarrassez vous du bois mort et prenez un nouveau départ.",
	"92" : "N’abusez pas des gens autour de vous. Traitez chacun équitablement.",
	"93" : "Recherchez des alliés ayant une bonne éthique du travail.",
	"64" : "Restructurez ce que vous devez conserver. Devenez plus efficient.",
	"95" : "Réjouissez-vous de vos nouveaux succès.",
	"66" : "Ne soyez pas arrogant envers ceux qui sont sous votre gouverne.",
	"realisation" : "****",
	},
"䷰" : {
	"nom" : "49. Ko / Ge",
	"titre" : "La mue / modifier, changer, Révolution",
	"resume" : "Introduisez de nouvelles idées dans votre vie.",
	"91" : "Planifiez bien vos buts et vos idées.",
	"62" : "Le temps est venu pour vous d’avancer. Mettez vos plans en action.",
	"93" : "Vous pourrez rencontrer de la résistance par rapport à vos idées. Cependant vous devez continuer à les mettre de l’avant et éventuellement elles seront acceptées.",
	"94" : "Corrigez vos erreurs dès que possible. Votre idée est acceptée.",
	"95" : "Tout va se passer selon vos plans.",
	"66" : "Bien que certain personnes voudraient vous voir échouer, poursuivez votre chemin et vous connaîtrez le succès.",
	"realisation" : "***",
	},
"䷱" : {
	"nom" : "50. Ting / Ding",
	"titre" : "Le Chaudron / trépied",
	"resume" : "Mettez vos plans en action. Les obstacles vont vous aider à les parfaire.",
	"61" : "Éliminez vos mauvaises habitudes et vous deviendrez plus productif.",
	"92" : "Ne prêtez pas attention à vos détracteurs. Il n’y a que votre opinion qui compte.",
	"93" : "Maintenant il est temps de mettre en œuvre de nouveaux projets.",
	"94" : "Corrigez vos erreurs, ainsi elles ne mettront pas en danger vos nouveaux projets.",
	"65" : "Éloignez vous des personnes négatives et égoïstes.",
	"96" : "Demeurez équilibré. Le fait d’être stricte et généreux va assurer votre succès.",
	"realisation" : "****",
	},
"䷲" : {
	"nom" : "51. Tshen / Zhen",
	"titre" : "Le tonnerre éveilleur / l’objet, l’ustensile / Tonnerre",
	"resume" : "Attendez-vous à des surprises étonnantes qui auront une grande influence dans votre vie.",
	"91" : "Des idées radicales sont sur le point de vous être présentées. Prenez le temps de bien les comprendre.",
	"62" : "Ceux qui sont dépassés pourront quitter pour un temps.",
	"63" : "Soyez ouverts aux idées nouvelles.",
	"94" : "Ne perdez pas votre temps à essayer de changer les personnes qui ne peuvent l’être.",
	"65" : "Soyez prêt à prendre des risques afin d’aller de l’avant.",
	"66" : "Ne résistez pas au changement. Il est en votre faveur.",
	"realisation" : "**",
	},
"䷳" : {
	"nom" : "52. Ken / Gen",
	"titre" : "La montagne immobile / l’arrêt / Immobilisation",
	"resume" : "Sollicitez l’attention de ceux que vous voulez prévenir.",
	"61" : "Offrez un avis unique et valable.",
	"62" : "Une relation avec quelqu’un sera bientôt ruinée si vous ne le prévenez pas.",
	"93" : "N’arrêtez pas ce qui est déjà en mouvement.",
	"64" : "Essayez d’arrêter un geste avant qu’il ne soit en cours.",
	"65" : "Choisissez bien vos mots avant de parler.",
	"96" : "Soyez diplomate et agissez avec intégrité lorsque vous donner votre avis à d’autres.",
	"realisation" : "**",
	},
"䷴" : {
	"nom" : "53. Tsien / Jian",
	"titre" : "Le progrès / progression en avant / Progression",
	"resume" : "Progressez à un rythme constant et raisonnable. Portez attention aux détails et demeurez engagé.",
	"61" : "Acceptez les critiques constructives. Améliorez ce que vous pouvez.",
	"62" : "Vous vous dirigez dans la bonne direction. Tout semble stable.",
	"93" : "Soyez prêt à vous défendre contre la malchance.",
	"64" : "Trouvez un refuge sûr. Récupérez et rechargez vos batteries avant de lancer de nouveaux projets. Planifiez soigneusement.",
	"95" : "Quand vous obtenez du succès, essayez quelque chose de nouveau.",
	"96" : "Utilisez les succès passés comme base pour la réussite de buts plus élevés.",
	"realisation" : "****",
	},
"䷵" : {
	"nom" : "54. Kouei mei / Gu Mei",
	"titre" : "L'épousée / mariage",
	"resume" : "Des temps difficiles vous ont tourmenté.",
	"91" : "Gardez votre cap.",
	"92" : "Ne vous attardez pas à des situations désagréables.",
	"63" : "Demeurez fier et passez à travers les temps durs.",
	"94" : "Vous serez accablé par les difficultés pendant un certain temps.",
	"65" : "Lorsque de nouvelles opportunités se présentent, acceptez les avec confiance. Vous agirez bien.",
	"66" : "Demeurez intègre malgré les difficultés.",
	"realisation" : "**",
	},
"䷶" : {
	"nom" : "55. Fong / Feng",
	"titre" : "La plénitude / grandeur / Abondance",
	"resume" : "Profitez de votre prospérité. Cependant, rappelez vous qu’avec les gains viennent les responsabilités. Dépensez intelligemment.",
	"91" : "Le temps va vous dire ce qui va résulter des nouvelles relations.",
	"62" : "Ignorez les ragots et les accusations stupides. Votre voie en est une bonne.",
	"93" : "Vous n’avez rien fait de mal, donc ne craignez pas les accusations des autres.",
	"94" : "Vos alliés feront la sourde oreille aux mauvaises rumeurs à votre sujet.",
	"65" : "Vous serez reconnu comme un actif.",
	"66" : "Faire étalage de votre prospérité vous mettra à dos votre famille et vos amis.",
	"realisation" : "*****",
	},
"䷷" : {
	"nom" : "56. Lou / Lu",
	"titre" : "L'errant /  voyageur, étranger / Voyage",
	"resume" : "Chérissez ces moments les plus mémorables de votre parcours de vie.",
	"61" : "Ne soyez pas avare, étroit d’esprit ou mesquin.",
	"62" : "Une belle route s’ouvre devant vous.",
	"93" : "Dans les situations difficiles faites preuve de retenue et soyez aimable.",
	"94" : "Vos jours se passeront de mieux en mieux.",
	"65" : "Recherchez de nouvelles opportunités.",
	"96" : "Ne vous réjouissez pas de la malchance des autres. Rappelez-vous que ça aurait pu être vous.",
	"realisation" : "***",
	},
"䷸" : {
	"nom" : "57. Souen / Xun",
	"titre" : "Le vent doux / entrer / Pénétrant",
	"resume" : "Communiquez avec les membres de votre groupe.",
	"61" : "N’hésitez pas, votre détermination va vous apporter du succès.",
	"92" : "Soyez honnête lorsque vous exprimez vos idées aux autres.",
	"93" : "Ne bousculer pas les gens avec vos idées, sinon vous serez étiqueté comme étant un fanatique.",
	"64" : "Ne laissez pas les revers vous arrêter. Demeurez positif et aller de l’avant.",
	"95" : "Réfléchissez à vos décisions avant de passer à l’action.",
	"96" : "Attendez vous à perdre des supporteurs lorsque vous irez de l’avant.",
	"realisation" : "****",
	},
"䷹" : {
	"nom" : "58. Touei / Dui",
	"titre" : "Le lac joyeux / plaire / Charme",
	"resume" : "Soyez généreux et favorisez les relations harmonieuses.",
	"91" : "Demeurez sincère et charmant. Soyez ouvert et accueillant.",
	"92" : "Accueillez divergences avec sincérité.",
	"63" : "Ne traitez pas les gens de manière superficielle. Soyez authentique envers vous et honnête envers eux.",
	"94" : "Essayez de résoudre les mésententes avec des compromis.",
	"95" : "Identifiez bien vos amis et ne vous confiez pas à vos ennemis.",
	"66" : "Récompensez un travail bien fait.",
	"realisation" : "****",
	},
"䷺" : {
	"nom" : "59. Hoan / Huan",
	"titre" : "La dispersion / séparation",
	"resume" : "Prenez votre situation en main et éliminez ce qui pourrait entraver votre progression.",
	"61" : "Agissez promptement avec détermination afin de progresser.",
	"92" : "Si une situation devient chaotique, gardez votre calme et employez vos talents à rectifier ce qui ne va pas.",
	"63" : "Renforcez la cohésion de votre groupe afin de surmonter les obstacles.",
	"64" : "Votre cause obtiendra des appuis. Soyez patient.",
	"95" : "Partagez votre prospérité avec ceux qui vous ont aidé à l’obtenir.",
	"96" : "Bien que la résolution de vos problèmes puisse être coûteuse, ils passeront.",
	"realisation" : "***",
	},
"䷻" : {
	"nom" : "60. Tsie / Jie",
	"titre" : "La modération / définir, régler / Limitation",
	"resume" : "Coupez dans les concessions jusqu’à ce que vous soyez remis en selle.",
	"91" : "Restez chez vous et coupez dans vos dépenses.",
	"92" : "Lorsqu’une opportunité se présente tirez en avantage. Soyez prudent, frugal, sans être mesquin.",
	"63" : "Établissez un budget que vous et vos partenaires respecterez.",
	"64" : "Ne vivez pas au-dessus de vos moyens. Épargnez.",
	"95" : "Soyez frugal. Concentrez-vous davantage sur votre dimension spirituelle.",
	"66" : "Ne soyez pas misérable. Dépensez de l’argent là où c’est nécessaire.",
	"realisation" : "**",
	},
"䷼" : {
	"nom" : "61. Tshong fou / Zhong Fu",
	"titre" : "La vérité intérieure / confiance, certitude /Confiance mutuelle",
	"resume" : "Développez la confiance mutuelle au sein de votre groupe. La confiance va accélérer votre réussite.",
	"91" : "Apprenez à faire confiance aux gens qui vous entourent. Donnez leurs le bénéfice du doute.",
	"92" : "Diriger équitablement et chacun appréciera votre succès.",
	"63" : "Vous êtes peut-être à un point tournant. Réfléchissez soigneusement à vos plans.",
	"64" : "Abordez sans délai les problèmes.",
	"95" : "Faites ce qui doit être fait pour gagner la confiance des gens qui vous entourent.",
	"96" : "Maintenant c’est le temps d’agir.",
	"realisation" : "*****",
	},
"䷽" : {
	"nom" : "62. Siao kuo / Xiao Guo",
	"titre" : "La prépondérance du petit / petit excès / Petit test",
	"resume" : "Essayez de simplifier les choses afin d’éclaircir la route vers de plus grands projets.",
	"61" : "N’outrepassez pas votre niveau d’autorité. Comprenez bien votre position.",
	"62" : "Lorsque nécessaire, acceptez des responsabilités supplémentaires sans vous plaindre. Servez vous de ces opportunités pour démontrer vos talents.",
	"93" : "N’agissez pas en outrepassant votre rang.",
	"94" : "N’outrepassez pas votre niveau d’autorité, sinon vous rencontrerez des problèmes.",
	"65" : "Agissez rapidement pour résoudre tout problème vous concernant.",
	"66" : "Outrepasser vos limites produira des conséquences sérieuses.",
	"realisation" : "***",
	},
"䷾" : {
	"nom" : "63. Ki tsi / Ji Ji",
	"titre" : "L'accomplissement / déjà établi / Après accomplissement",
	"resume" : "Procédez prudemment. Bien que votre chemin semble maintenant facile, des problèmes peuvent survenir et vous projeter hors piste.",
	"91" : "Attendez vous à retrouver une route cahoteuse. Garder le cap et le succès vous sourira.",
	"62" : "Tout ce que vous perdrez sera regagné.",
	"93" : "Entourez vous de gens intelligents. Ils vous aideront à connaître le succès.",
	"64" : "N’accordez votre confiance qu’à ceux qui en sont digne.",
	"95" : "Aller de l’avant vers vos buts. La route semble difficile mais vous réussirez.",
	"66" : "Le moment venu vos buts seront atteints.",
	"realisation" : "***",
	},
"䷿" : {
	"nom" : "64. Vi tsi / Wei Ji",
	"titre" : "Vers l'accomplissement / pas encore établi / Avant l’accomplissement",
	"resume" : "Persévérez, soyez courageux et attentif.",
	"61" : "Perfectionnez vos habiletés et renforcez votre position tranquille.",
	"92" : "Ne prenez pas de risque en ce moment.",
	"63" : "Persévérez et une grosse opportunité vous devrait s’offrir.",
	"94" : "Apprenez ne vos ennemies autant que de vos alliés. Ces leçons vont assurer votre succès.",
	"65" : "Soyez fidèle à vos principes et vos buts seront atteints.",
	"96" : "Ne soyez pas fanatique envers quoique ce soit. Soyez ouvert au changement.",
  "realisation" : "****",
  }
}


function getOracle(){
  return oracle
}
function getProbabiliteRealisation(){
  return probabiliteRealisation
}
function getBinaryToHexagramme(){
  return binaryToHexagramme
}

module.exports.getOracle = getOracle
module.exports.getBinaryToHexagramme = getBinaryToHexagramme
module.exports.getProbabiliteRealisation = getProbabiliteRealisation
